### ISSUE TITLE
[FIX] I can't login to account [email]

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#249]
![CPE](https://github.com/sws2apps/cpe-sws/assets/76891864/eda209a4-88fc-4643-bb2f-699aa406cf5c)

**Comment by rhahao** [comment]
Thanks for your report @joaochris! I will take a look at this.

**Comment by rhahao** [comment]
@joaochris: I could not replicate this issue on my end. Seeing the error message, it seems like something in the browser is preventing CPE to get the resource it needs in order to authenticate you. Not sure about what could happen in your case, but some browser for example has a feature to block fingerprint access for a website, or with help of an extension. But CPE needs the fingerprint access for authentication. Can you confirm if something was changed recently to the browser you use to open CPE?

**Comment by joaochris** [comment]
It was an extension! I turned it off and it worked. Thanks!
