### ISSUE TITLE
No fill-in field in Congregation Bible Study in "Review" studies

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#8]
Some studies do not require reading. From what I observed, the studies that contain the word "Review" do not require a reader. Would it also be possible for the fill box not to appear?

![Screenshot_17](https://user-images.githubusercontent.com/76891864/217565469-b967bb27-8dc8-44d0-a0fa-af0798e7e04c.png)

**Comment by rhahao** [comment]
Hi @joaochris, as you may have already noticed, I’ve also added a check which points of the _lff_ we will be considering for CBS. Basically, when the points start with "1", CPE displays the reader, otherwise, it will hide it. If there is any unexpected behavior because of this, please report it by creating a new issue. 😊
